spring:
    datasource:
        url: jdbc:mysql://localhost:3306/openapi-db?useSSL=false
        username: user
        password: P@ssword
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        show-sql: true
        hibernate:
            ddl-auto: update
server:
    servlet:
        context-path: /api/v1
springdoc:
    swagger-ui:
        path: /swagger-ui.html
        display-request-duration: true
        group-order: ALPHA
        operationsSorter: method
        disable-swagger-default-url: true
    api-docs:
        path: /api-docs
